=== TheVict0r/epam_JWD_task_8_xml/pravdivets-task8xml/src/main/webapp/WEB-INF/data/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="tariffs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="tariff" type="Tariff" 
					minOccurs="1"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Tariff">
		<xs:sequence>
			<xs:element name="ID" type="xs:ID" />
			<xs:element name="name" type="xs:string" /> <!--Название тарифа -->
			<xs:element name="operator" type="xs:string" /> <!--Мобильный оператор -->
			
			<xs:element name="status" default="in service"> <!-- доступный для подключения / архивный -->
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="in service" />
						<xs:enumeration value="archived" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			
			<xs:element name="release_date" type="xs:date"/> <!-- дата выхода нв рынок -->
			
			<xs:element name="regular_payment"> <!--Абонентская плата -->
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			
			<xs:element name="connection_fee" minOccurs="0"> <!--Плата за подключение -->
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			
			<xs:element name="calls" type="Calls" />

			<xs:element name="favourite_numbers" minOccurs="0"> <!--Кол-во любимых номеров -->
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="messages" type="Messages" />

		</xs:sequence>

	</xs:complexType>

	<xs:complexType name="Calls"> <!-- Стоимость звонков -->
		<xs:sequence>
			<xs:element name="within_network"> <!-- Внутри сети -->
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="other_networks"> <!-- На другие сети -->
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minExclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="landlines"> <!-- На городскую стационарную сеть -->
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minExclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="abroad"> <!-- Международные -->
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minExclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="videocall"> <!-- Видео-звонки -->
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minExclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

		</xs:sequence>

		<xs:attribute name="billing_model" default="by 1 sec" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="by 1 sec" />
					<xs:enumeration value="by 1 sec after 1st minute" />
					<xs:enumeration value="by 12 sec" />
					<xs:enumeration value="by 1 min" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>

	</xs:complexType>

	<xs:complexType name="Messages">
		<xs:sequence>
			<xs:element name="SMS">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minExclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="MMS">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minExclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== TheVict0r/epam_JWD_task_8_xml/pravdivets-task8xml/src/main/webapp/WEB-INF/data/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="tariffs.xsd">
		
<tariff>
	<ID>id1</ID>
	<name>Tariff-1</name>
	<operator>B-2</operator>
	<status>in service</status>
	<release_date>2020-07-11</release_date>
	<regular_payment>1000</regular_payment> <!-- все цены в копейках -->
	<connection_fee>1000</connection_fee>
	<calls billing_model="by 1 sec">
		<within_network>20</within_network>
		<other_networks>40</other_networks>
		<landlines>40</landlines>
		<abroad>60</abroad>
		<videocall>50</videocall>
	</calls>
	<favourite_numbers>3</favourite_numbers>
	<messages>
		<SMS>30</SMS>
		<MMS>35</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id2</ID>
	<name>Tariff-2</name>
	<operator>B-2</operator>
	<status>in service</status>
	<release_date>2018-05-01</release_date>
	<regular_payment>1500</regular_payment> <!-- все цены в копейках -->
	<connection_fee>2000</connection_fee>
	<calls billing_model="by 1 min">
		<within_network>25</within_network>
		<other_networks>45</other_networks>
		<landlines>45</landlines>
		<abroad>65</abroad>
		<videocall>55</videocall>
	</calls>
	<favourite_numbers>5</favourite_numbers>
	<messages>
		<SMS>40</SMS>
		<MMS>45</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id3</ID>
	<name>Tariff-4</name>
	<operator>B-2</operator>
	<status>in service</status>
	<release_date>2021-03-11</release_date>
	<regular_payment>800</regular_payment> <!-- все цены в копейках -->
	<connection_fee>800</connection_fee>
	<calls billing_model="by 1 sec">
		<within_network>0</within_network>
		<other_networks>20</other_networks>
		<landlines>20</landlines>
		<abroad>80</abroad>
		<videocall>45</videocall>
	</calls>
	<favourite_numbers>3</favourite_numbers>
	<messages>
		<SMS>20</SMS>
		<MMS>35</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id4</ID>
	<name>Tariff-4</name>
	<operator>B-2</operator>
	<status>archived</status>
	<release_date>2015-02-21</release_date>
	<regular_payment>3000</regular_payment> <!-- все цены в копейках -->
	<connection_fee>3000</connection_fee>
	<calls billing_model="by 1 min">
		<within_network>40</within_network>
		<other_networks>60</other_networks>
		<landlines>60</landlines>
		<abroad>100</abroad>
		<videocall>150</videocall>
	</calls>
	<messages>
		<SMS>20</SMS>
		<MMS>25</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id5</ID>
	<name>Tariff-5</name>
	<operator>B-2</operator>
	<status>archived</status>
	<release_date>2017-11-07</release_date>
	<regular_payment>1500</regular_payment> <!-- все цены в копейках -->
	<connection_fee>1500</connection_fee>
	<calls billing_model="by 1 sec after 1st minute">
		<within_network>20</within_network>
		<other_networks>40</other_networks>
		<landlines>40</landlines>
		<abroad>60</abroad>
		<videocall>50</videocall>
	</calls>
	<messages>
		<SMS>10</SMS>
		<MMS>45</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id6</ID>
	<name>Tariff-6</name>
	<operator>STM</operator>
	<status>in service</status>
	<release_date>2020-07-01</release_date>
	<regular_payment>1100</regular_payment> <!-- все цены в копейках -->
	<connection_fee>1100</connection_fee>
	<calls billing_model="by 1 sec">
		<within_network>25</within_network>
		<other_networks>45</other_networks>
		<landlines>45</landlines>
		<abroad>65</abroad>
		<videocall>55</videocall>
	</calls>
	<favourite_numbers>2</favourite_numbers>
	<messages>
		<SMS>33</SMS>
		<MMS>35</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id7</ID>
	<name>Tariff-7</name>
	<operator>STM</operator>
	<status>in service</status>
	<release_date>2019-01-17</release_date>
	<regular_payment>3200</regular_payment> <!-- все цены в копейках -->
	<connection_fee>3500</connection_fee>
	<calls billing_model="by 12 sec">
		<within_network>10</within_network>
		<other_networks>20</other_networks>
		<landlines>20</landlines>
		<abroad>60</abroad>
		<videocall>40</videocall>
	</calls>
	<favourite_numbers>5</favourite_numbers>
	<messages>
		<SMS>30</SMS>
		<MMS>35</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id8</ID>
	<name>Tariff-8</name>
	<operator>STM</operator>
	<status>in service</status>
	<release_date>2018-04-21</release_date>
	<regular_payment>1600</regular_payment> <!-- все цены в копейках -->
	<connection_fee>1600</connection_fee>
	<calls billing_model="by 1 min">
		<within_network>30</within_network>
		<other_networks>40</other_networks>
		<landlines>40</landlines>
		<abroad>65</abroad>
		<videocall>53</videocall>
	</calls>
	<favourite_numbers>10</favourite_numbers>
	<messages>
		<SMS>30</SMS>
		<MMS>35</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id9</ID>
	<name>Tariff-9</name>
	<operator>STM</operator>
	<status>archived</status>
	<release_date>2015-12-27</release_date>
	<regular_payment>5000</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 sec">
		<within_network>8</within_network>
		<other_networks>12</other_networks>
		<landlines>12</landlines>
		<abroad>60</abroad>
		<videocall>30</videocall>
	</calls>
	<favourite_numbers>3</favourite_numbers>
	<messages>
		<SMS>10</SMS>
		<MMS>15</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id10</ID>
	<name>Tariff-10</name>
	<operator>Monallog</operator>
	<status>archived</status>
	<release_date>2012-07-11</release_date>
	<regular_payment>3000</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 min">
		<within_network>0</within_network>
		<other_networks>50</other_networks>
		<landlines>50</landlines>
		<abroad>80</abroad>
		<videocall>90</videocall>
	</calls>
	<messages>
		<SMS>40</SMS>
		<MMS>45</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id11</ID>
	<name>Tariff-11</name>
	<operator>Monallog</operator>
	<status>archived</status>
	<release_date>2013-05-17</release_date>
	<regular_payment>4000</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 min">
		<within_network>0</within_network>
		<other_networks>45</other_networks>
		<landlines>45</landlines>
		<abroad>75</abroad>
		<videocall>85</videocall>
	</calls>
	<messages>
		<SMS>40</SMS>
		<MMS>45</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id12</ID>
	<name>Tariff-12</name>
	<operator>Monallog</operator>
	<status>archived</status>
	<release_date>2013-07-11</release_date>
	<regular_payment>5000</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 min">
		<within_network>0</within_network>
		<other_networks>40</other_networks>
		<landlines>40</landlines>
		<abroad>70</abroad>
		<videocall>80</videocall>
	</calls>
	<messages>
		<SMS>40</SMS>
		<MMS>45</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id13</ID>
	<name>Tariff-13</name>
	<operator>Monallog</operator>
	<status>archived</status>
	<release_date>2013-07-11</release_date>
	<regular_payment>6000</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 min">
		<within_network>0</within_network>
		<other_networks>35</other_networks>
		<landlines>35</landlines>
		<abroad>65</abroad>
		<videocall>75</videocall>
	</calls>
	<messages>
		<SMS>40</SMS>
		<MMS>45</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id14</ID>
	<name>Tariff-14</name>
	<operator>Monallog</operator>
	<status>archived</status>
	<release_date>2013-07-11</release_date>
	<regular_payment>7000</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 min">
		<within_network>0</within_network>
		<other_networks>30</other_networks>
		<landlines>30</landlines>
		<abroad>60</abroad>
		<videocall>70</videocall>
	</calls>
	<messages>
		<SMS>40</SMS>
		<MMS>45</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id15</ID>
	<name>Tariff-15</name>
	<operator>Monallog</operator>
	<status>archived</status>
	<release_date>2013-07-11</release_date>
	<regular_payment>7500</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 min">
		<within_network>0</within_network>
		<other_networks>25</other_networks>
		<landlines>25</landlines>
		<abroad>55</abroad>
		<videocall>65</videocall>
	</calls>
	<messages>
		<SMS>40</SMS>
		<MMS>45</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id16</ID>
	<name>Tariff-10</name>
	<operator>Monallog</operator>
	<status>in service</status>
	<release_date>2015-07-11</release_date>
	<regular_payment>2000</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 min">
		<within_network>10</within_network>
		<other_networks>30</other_networks>
		<landlines>30</landlines>
		<abroad>50</abroad>
		<videocall>50</videocall>
	</calls>
	<messages>
		<SMS>20</SMS>
		<MMS>25</MMS>
	</messages>
</tariff>
	
<tariff>
	<ID>id17</ID>
	<name>Tariff-17</name>
	<operator>Monallog</operator>
	<status>in service</status>
	<release_date>2015-07-11</release_date>
	<regular_payment>3000</regular_payment> <!-- все цены в копейках -->
	<calls billing_model="by 1 min">
		<within_network>10</within_network>
		<other_networks>25</other_networks>
		<landlines>25</landlines>
		<abroad>50</abroad>
		<videocall>50</videocall>
	</calls>
	<messages>
		<SMS>20</SMS>
		<MMS>25</MMS>
	</messages>
</tariff>
	

</tariffs>
